# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-01 19:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=20)),
                ('middlename', models.CharField(max_length=20)),
                ('ssn', models.CharField(max_length=9)),
                ('dob', models.DateTimeField()),
                ('license', models.CharField(max_length=15)),
                ('license_state', models.CharField(max_length=12)),
                ('occupation', models.CharField(max_length=30)),
                ('membership', models.CharField(max_length=25)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memberinfo.Account')),
            ],
        ),
    ]
