# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-02 13:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberinfo', '0002_auto_20160602_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='M', max_length=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='membership',
            field=models.CharField(choices=[('1', 'UM Student'), ('2', 'UM Grad Student'), ('3', 'UM Hospital'), ('4', 'UM Faculty/Staff'), ('5', 'Alumni'), ('6', 'Retiree'), ('7', 'WCC'), ('8', 'Family Member'), ('9', 'Current Member'), ('10', 'Other')], default='1', max_length=2),
        ),
    ]
